### ISSUE TITLE
Build error after 1a732c7c03155a7e6fec48ff1db84f0e9e36fcf7

### ISSUE THREAD

**Issue by darthlukan** [darthlukan/gobot#8]
After merging the pull request from @BlackNoxis the build started failing on Drone.io.

Fails with: 

```
    $ git clone git://github.com/darthlukan/gobot.git /home/ubuntu/src/github.com/darthlukan/gobot 
    Cloning into '/home/ubuntu/src/github.com/darthlukan/gobot'...
    $ go version
    go version go1.2 linux/amd64
    $ go get
    # github.com/thoj/go-ircevent
    ../../thoj/go-ircevent/irc.go:365: undefined: tls.DialWithDialer
```
